broker amqps://MSC-GEOMET@hpfx.collab.science.gc.ca/
exchange xs_MSC-GEOMET_DMS_${HOSTNAME}
queueName q_${BROKER_USER}.${PROGRAM}.${CONFIG}.${HOSTNAME}
instances 2

subtopic data.geomet.feeds.dms-alpha.alerts.#
subtopic data.geomet.feeds.dms-dev.alerts.#
subtopic data.geomet.feeds.dms-stage.alerts.#

download False
report   False
mirror    True

directory /
accept .*

callback ${MSC_PYGEOAPI_METPX_EVENT_FILE_PY}