###################################################################
#
# Author: Tom Kralidis <tom.kralidis@ec.gc.ca>
#
# Copyright (c) 2023 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
###################################################################

services:
  msc-pygeoapi:
    image: eccc-msc/msc-pygeoapi:nightly
    container_name: msc-pygeoapi-nightly
    build: 
      context: ..
    network_mode: host
    env_file:
      - default.env
    volumes:
      - "/datalocal:/datalocal:ro"
      - "/data/geomet/feeds:/data/geomet/feeds:ro"
      - "/data/geomet/local:/data/geomet/local:ro"
      - "/data-san/geomet/feeds:/data-san/geomet/feeds:ro"
      - "/data-san/geomet/local:/data-san/geomet/local:ro"
      - "/opt/geomet-climate:/opt/geomet-climate:ro"
      - "/opt/geomet-climate/vrt:/opt/geomet-climate/vrt:ro"

networks:
  default:
    name: geomet_default
    driver: bridge