deploy/default/msc-pygeoapi-config.yml opt/msc-pygeoapi/conf
deploy/default/msc-pygeoapi-openapi.yml opt/msc-pygeoapi/conf
deploy/default/msc-pygeoapi.conf opt/msc-pygeoapi/etc/apache2
deploy/default/msc-pygeoapi.wsgi opt/msc-pygeoapi/app
deploy/default/sarracenia/*.conf opt/msc-pygeoapi/etc/sarracenia
msc_pygeoapi/event.py opt/msc-pygeoapi
debian/schemas.opengis.net opt/msc-pygeoapi
theme opt/msc-pygeoapi
